server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/person
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Kv139@postgres
  jpa:
    hibernate:
      ddl-auto: update
